//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data.Storage
{
    using System;
    using System.Collections.Generic;
    
    public partial class stores
    {
        public int id { get; set; }
        public int drink_id { get; set; }
        public int qty { get; set; }
    
        public virtual drinks drink { get; set; }
    }
}
